### ISSUE TITLE
ContentProcessorDofn Type Issue

### ISSUE THREAD

**Issue by sailaxman** [GoogleCloudPlatform/dlp-dataflow-deidentification#38]
Hi There, When I cloned the repo and following the readme instructions. The runs are failing. 

Exception in thread "main" java.lang.IllegalArgumentException: com.google.swarm.tokenization.common.CSVContentProce
ssorDoFn, @ProcessElement processElement(ProcessContext, OffsetRangeTracker): Has tracker type OffsetRangeTracker, 
but the DoFn's tracker type must be of type RestrictionTracker.
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures$ErrorReporter.throwIllegalArgument(DoFnSignatures.java:1495)
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures$ErrorReporter.checkArgument(DoFnSignatures.java:1500)
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.verifySplittableMethods(DoFnSignatures.java:595)
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.parseSignature(DoFnSignatures.java:474)
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.lambda$getSignature$0(DoFnSignatures.java:140)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at org.apache.beam.sdk.transforms.reflect.DoFnSignatures.getSignature(DoFnSignatures.java:140)
        at org.apache.beam.sdk.transforms.ParDo.validate(ParDo.java:547)
        at org.apache.beam.sdk.transforms.ParDo.of(ParDo.java:397)
        at com.google.swarm.tokenization.CSVStreamingPipeline.doTokenization(CSVStreamingPipeline.java:71)
        at com.google.swarm.tokenization.CSVStreamingPipeline.main(CSVStreamingPipeline.java:109)

**Comment by JD-V** [comment]
@sailaxman Why was this closed?
is it something wrong that you did? because I am also facing this issue
